import pandas as pd
from pathlib import Path
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_FILE = PROJECT_ROOT / "data" / "processed" / "dataset_preprocessed.csv"

# ==============Load and clean data==============
print("Loading dataset...")
df = pd.read_csv(DATA_FILE)

df["text_combined"] = df["text_combined"].fillna("").astype(str)
df["model"]  = df["model"].fillna("none").astype(str).str.strip().str.lower()
df["source"] = df["source"].fillna("").astype(str).str.strip().str.lower()

# ==================Harder / realistic train-test split==========================
# test set is all deepseek-generated phishing so it tests generalisation to a model the classifier has never seen, which is more realistic than a random split
TEST_MODEL = "deepseek"

# separate phishing and legitimate emails so each can be split independently
phishing_df = df[df["label"] == 1]
legit_df    = df[df["label"] == 0]

# training phishing: all emails NOT generated by the held-out model
# test phishing: only emails generated by the held-out model
train_phishing = phishing_df[phishing_df["model"] != TEST_MODEL]
test_phishing  = phishing_df[phishing_df["model"] == TEST_MODEL]

# match test set size to keep class balance 50/50
test_legit  = legit_df.sample(n=len(test_phishing), random_state=42)
train_legit = legit_df.drop(test_legit.index)

# combine phishing and legitimate emails into final train and test sets
# shuffle both sets so no ordering artefacts influence training or evaluation
train_df = pd.concat([train_phishing, train_legit]).sample(frac=1, random_state=42)
test_df  = pd.concat([test_phishing,  test_legit]).sample(frac=1, random_state=42)

print(f"\nTrain: {len(train_df)}  Test: {len(test_df)}")
print("\nTest class balance:")
print(test_df["label"].value_counts())

# ===================Features and labels======================
X_train = train_df["text_combined"]
y_train = train_df["label"]
X_test  = test_df["text_combined"]
y_test  = test_df["label"]

# ===================Tokenisation=================
# vocab cap where rarer words are discarded
max_words = 10000

# pad/shorten to this length
max_len = 200

# fit on training corpus only so no test data leaks into the vocabulary
# oov_token="<OOV>" maps unseen words to a reserved index rather than dropping them
print("\nTokenising...")
tokeniser = Tokenizer(num_words=max_words, oov_token="<OOV>")
tokeniser.fit_on_texts(X_train)

# xonvert each email from a string into a list of integer tokens
X_train_seq = tokeniser.texts_to_sequences(X_train)
X_test_seq  = tokeniser.texts_to_sequences(X_test)

# pad or shorten every sequence to max_len.
# padding="post" appends zeros to the end, preserving the start of each email.
X_train_pad = pad_sequences(X_train_seq, maxlen=max_len, padding="post")
X_test_pad  = pad_sequences(X_test_seq,  maxlen=max_len, padding="post")

# ================Model architecture===============
# BiLSTM reads both directions and is useful when suspicious phrasing can appear anywhere in the email rather than just at the start
print("\nBuilding model...")
model = Sequential([
    # embedding layer learns a dense 64-dimensional vector for each token
    Embedding(max_words, 64),
    Bidirectional(LSTM(64)),

    # dropout zeros 30% of activations during training to reduce overfitting
    Dropout(0.3),

    # fully connected layer to learn a non-linear combination of LSTM features
    Dense(32, activation="relu"),

    # single sigmoid output, produces a probability in 0 & 1
    # > 0.5 is phishing
    Dense(1, activation="sigmoid")
])

# binary_crossentropy is the standard loss function for binary classification
# adam is an adaptive learning rate optimiser well suited to sequence models
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# =================Training========================
# train for 3 epochs
# validation_split=0.2 reserves 20% of the training data to monitor
# validation loss and accuracy after each epoch
print("\nTraining model...")
model.fit(X_train_pad, y_train, epochs=3, batch_size=32, validation_split=0.2, verbose=1)


# =================Evaluation=================
# evaluating on phishing from an unseen model + balanced legit emails
print("\nEvaluating on held-out model...")
y_pred = (model.predict(X_test_pad) > 0.5).astype(int)

# recall on class 1 matters most — a missed phishing email costs more than a false alarm
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
